In [38]:
from foreduce.vampire.parser import read_string

read_string("""
% Running in auto input_syntax mode. Trying TPTP
[SA] new: 1. lives(agatha) [input]
[SA] new: 2. lives(butler) [input]
[SA] new: 3. lives(charles) [input]
[SA] new: 4. ~richer(X0,X1) | ~killed(X0,X1) [input]
[SA] new: 5. ~hates(charles,X2) | ~hates(agatha,X2) [input]
[SA] new: 6. ~hates(X3,charles) | ~hates(X3,butler) | ~hates(X3,agatha) [input]
[SA] new: 7. hates(agatha,agatha) [input]
[SA] new: 8. hates(agatha,charles) [input]
[SA] new: 9. hates(X4,X5) | ~killed(X4,X5) [input]
[SA] new: 10. hates(butler,X6) | ~hates(agatha,X6) [input]
[SA] new: 11. hates(butler,X7) | richer(X7,agatha) | ~lives(X7) [input]
[SA] new: 12. goal_0 | killed(charles,agatha) | killed(butler,agatha) [input]
[SA] new: 13. ~goal_0 [input]

""")

(lives(agatha)
 lives(butler)
 lives(charles)
 ~richer(X0, X1) | ~killed(X0, X1)
 ~hates(charles, X2) | ~hates(agatha, X2)
 ~hates(X3, charles) | ~hates(X3, butler) | ~hates(X3, agatha)
 hates(agatha, agatha)
 hates(agatha, charles)
 hates(X4, X5) | ~killed(X4, X5)
 hates(butler, X6) | ~hates(agatha, X6)
 hates(butler, X7) | richer(X7, agatha) | ~lives(X7)
 goal_0 | killed(charles, agatha) | killed(butler, agatha)
 ~goal_0,
 [[], [], [], [], [], [], [], [], [], [], [], [], []])

In [1]:
VAMPIRE_PATH = '/home/apluska/.vampire/bin/vampire_z3_rel_static_casc2023_6749'
TPTP_PATH = '/home/apluska/TPTP-v8.2.0/'

In [2]:
import pexpect

In [220]:
process.close()

In [217]:
from foreduce.fol.logic import Problem

process = pexpect.spawn(
    VAMPIRE_PATH +\
    ' ./problems/PUZ/PUZ001-1.p' +\
    ' --manual_cs on' +\
    ' --show_new on' +\
    ' --proof off' +\
    ' --avatar off' +\
    ' -t 0'
)
i=1
problem, tree = Problem(), []

In [221]:
for _ in range(100):
    branch = process.expect(['Pick a clause:\r\n', '[#\\$] '])
    match branch:
        case 0:
            string = str(process.before, encoding='utf-8')
            string = string[string.find('\n')+1:].replace('\r\n', '\n')
            if string and not 'User error' in string:
                _problem, _tree = read_string(string)
                problem.clauses += _problem.clauses
                tree += [[idx + len(tree) for idx in idy] for idy in _tree]
            process.sendline(str(i))
            i += 1
        case 1:
            print('Done')

<>:2: SyntaxWarning: invalid escape sequence '\$'
<>:2: SyntaxWarning: invalid escape sequence '\$'
/tmp/ipykernel_1864797/3600298485.py:2: SyntaxWarning: invalid escape sequence '\$'
  branch = process.expect(['Pick a clause:\r\n', '[#\$] '])


ValueError: I/O operation on closed file.

In [214]:
process.before

b'14\r\nUser error: No clause in Passive has id 14!\r\n'

In [179]:
string = str(process.before, encoding='utf-8')
string = string[string.find('\n')+1:].replace('\r\n', '\n')
string

'[SA] new: 33. ~killed(butler,agatha) [resolution 30,4]\n[SA] new: 34. $false [subsumption resolution 33,28]\n% Refutation found. Thanks to Tanya!\n% SZS status Unsatisfiable for PUZ001-1\n% ------------------------------\n% Version: Vampire 4.8 (commit 8d999c135 on 2023-07-12 16:43:10 +0000)\n% Linked with Z3 4.9.1.0 6ed071b44407cf6623b8d3c0dceb2a8fb7040cee z3-4.8.4-6427-g6ed071b44\n% Termination reason: Refutation\n\n% Memory used [KB]: 511\n% Time elapsed: 302.920 s\n% ------------------------------\n% ------------------------------\n31\n32\n33\n'

In [122]:
from foreduce.vampire.parser import read_string

problem, tree = read_string(string)

In [177]:
process.sendline(str(i))
i+=1

In [50]:
from foreduce.vampire.parser import read_string

read_string(

(lives(agatha)
 lives(butler)
 lives(charles)
 ~richer(X0, X1) | ~killed(X0, X1)
 ~hates(charles, X2) | ~hates(agatha, X2)
 ~hates(X3, charles) | ~hates(X3, butler) | ~hates(X3, agatha)
 hates(agatha, agatha)
 hates(agatha, charles)
 hates(X4, X5) | ~killed(X4, X5)
 hates(butler, X6) | ~hates(agatha, X6)
 hates(butler, X7) | richer(X7, agatha) | ~lives(X7)
 goal_0 | killed(charles, agatha) | killed(butler, agatha)
 ~goal_0,
 [[], [], [], [], [], [], [], [], [], [], [], [], []])

In [3]:
import subprocess
import os
from tqdm.auto import tqdm

outputs = []
for file in tqdm(os.listdir(TPTP_PATH + 'Problems/PUZ/')):
    args = [VAMPIRE_PATH, TPTP_PATH + 'Problems/PUZ/' + file,  '--show_new', 'on', '--include', TPTP_PATH, '-t', '0.1', '--avatar', 'off', '--proof', 'off']
    result = subprocess.run(args, capture_output=True, text=True, timeout=2)
    outputs.append(result.stdout)

/home/apluska/miniconda3/envs/foreduce/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
  0%|          | 0/243 [00:00<?, ?it/s]

100%|██████████| 243/243 [00:23<00:00, 10.38it/s]


In [2]:
from foreduce.vampire.parser import read_file as read_vampire

problem, tree = read_vampire('./proofs/PUZ/PUZ001-1.p')

In [3]:
from foreduce.transformer.tokenizer import TokenConfig
from foreduce.data.data import ProofTokens

config = TokenConfig()
dataset = ProofTokens(config)
dataset.add_proof(problem, tree)

In [4]:
from foreduce.transformer.embedding import FormulaEmbedding

embedding = FormulaEmbedding(config)

/home/apluska/miniconda3/envs/foreduce/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [5]:
x, y, target = dataset[:2]

embedding(x).shape

torch.Size([2, 64])

In [2]:
from foreduce.transformer.tokenizer import ProofTokenizer, TokenConfig

ProofTokenizer(TokenConfig())(problem, tree)

(tensor([[ 1, 31, 16,  ...,  0,  0,  0],
         [ 1, 31, 16,  ...,  0,  0,  0],
         [ 1, 31, 16,  ...,  0,  0,  0],
         ...,
         [ 1, 47,  9,  ...,  0,  0,  0],
         [ 1, 47,  9,  ...,  0,  0,  0],
         [ 1, 47,  9,  ...,  0,  0,  0]], dtype=torch.int32),
 tensor([[ 1, 31,  9,  ...,  0,  0,  0],
         [ 1, 31, 20,  ...,  0,  0,  0],
         [ 1,  4, 47,  ...,  0,  0,  0],
         ...,
         [ 1, 47,  9,  ...,  0,  0,  0],
         [ 1,  4, 46,  ...,  0,  0,  0],
         [ 1,  4, 46,  ...,  0,  0,  0]], dtype=torch.int32),
 tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 