In [1]:
from counter_model import *

/home/apluska/miniconda3/envs/foreduce/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
model = MambaModel.load_from_checkpoint("mamba-counter.ckpt").cuda().eval()

In [23]:
model.inference()

In [24]:
from numpy import random

i = random.randint(0, 2**32)
digits = [int(d) for d in f"{i:032b}"]
digits

[0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1]

In [25]:
model.step(torch.tensor([[[5] + digits]]).cuda()).argmax(-1)

tensor([[[0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
          0, 1, 0, 1, 1, 0, 1, 1, 1]]], device='cuda:0')

In [12]:
dataset = SequenceDataset(10000, 50, .1, .0, .0, .01)

In [22]:
dataset[0:1][0][0][0]

tensor([5, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
        0, 0, 0, 0, 1, 0, 0, 0, 1])

In [20]:
model(dataset[0:1][0].cuda())[0, 0].argmax(-1)

tensor([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
        0, 0, 0, 1, 0, 0, 0, 1], device='cuda:0')