In [1]:
from foreduce.transformer.model import Transformer
model = Transformer.load_from_checkpoint(
    'checkpoints/FO-[4,4,2]-[4,2]-4-100000-1-epoch=00.ckpt'
).cpu().eval()

In [2]:
from foreduce.fol.random import *
from foreduce.transformer.modelargs import *
from foreduce.transformer.data import FirstOrderConfig, FirstOrderDataset
from foreduce.transformer.modelargs import ModelArgs

In [26]:
margs = ModelArgs()
mapping = margs.default_mapping()
data = FirstOrderDataset(FirstOrderConfig(margs, derivation_depth=1))
entry = 3
data0 = [int(i) for i in data[entry][0]]
axiom_index = int((data[entry][1] == 1).nonzero()[0]) + 1
solution_index = int((data[entry][1] == 1).nonzero()[-1]) + 1

In [28]:
p = margs.decode(data0[:axiom_index], mapping)
print(p)

p2_0(f2_0(X3, c_1), f2_1(c_0, c_2))
¬p2_0(f2_0(c_3, c_1), f2_1(c_0, X1))


In [29]:
s = margs.decode(data0[axiom_index:solution_index], mapping)
s.clauses

(p2_0(f2_0(c_3, c_1), f2_1(c_0, c_2)), ¬p2_0(f2_0(c_3, c_1), f2_1(c_0, c_2)))

In [30]:
clause = margs.next_clause(p, mapping, model)
clause

p2_0(f2_0(c_3, c_1), f2_1(c_0, c_2))

In [31]:
margs.next_clause(Problem(*p.clauses, clause), mapping, model)

¬p2_0(f2_0(c_3, c_1), f2_1(c_0, c_2))

In [10]:
from foreduce.transformer.data import *

data = FirstOrderDataset(FirstOrderConfig(margs))
x, mask = data[:1]

In [11]:
preds = model(x)[:,1:,:]

In [32]:
model(torch.tensor([rp.encode(mapping) + [2] + [0] * (margs.seq_len - 1 - len(rp.encode(mapping)))])).argmax(-1)[0, 42]

tensor(4)

In [17]:
len(rp.encode(mapping))

42

In [21]:
preds[0, 40].argmax()

tensor(2)

In [16]:
y.argmax(dim=1)[42]

tensor(23)

In [16]:
encoding = rp.encode(mapping)

In [17]:
input = encoding + [0] * (margs.seq_len - len(encoding))

In [34]:
x[:, :-1]

tensor([[ 2, 19, 24, 21,  1,  0,  3, 19, 24, 22,  1,  2, 18,  9, 23,  1,  0,  2,
         20, 24, 12,  5,  1,  3, 18,  9, 23,  1,  0,  2,  4, 22, 22,  1,  0,  3,
         20, 23, 12,  5,  1,  0,  2, 19, 24, 11, 23,  1,  0,  3, 19, 24, 11, 23,
          1,  2, 18,  9, 23,  1,  0,  2, 20,  7, 12,  5,  1,  3, 18,  9, 23,  1,
          0,  2,  4,  7,  7,  1,  0,  3, 20,  7, 12,  5,  1,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0]])

In [50]:
model(x).argmax(dim=2)

tensor([[ 0,  7,  7, 24, 21,  0,  0,  3, 19, 24, 22, 17,  2, 18,  9, 23,  0,  0,
          2, 20, 24, 12,  5,  1,  3, 18,  9, 23,  0,  0,  2,  4, 22, 22,  1,  0,
          3, 20, 23, 12,  5,  0,  0,  2, 19, 24, 11, 23,  1,  0,  3, 19, 24, 11,
         23,  1,  2, 18,  9, 23,  1,  0,  2, 20,  7, 12,  5,  1,  3, 18,  9, 23,
          1,  0,  2,  4,  7,  7,  1,  0,  3, 20,  7, 12,  5,  1,  0,  0,  1,  0,
          0,  1,  0, 12,  4,  1,  0,  2,  1,  1, 12, 12,  1,  0, 16,  1,  2,  0,
          1, 22,  0,  4,  1, 16, 12,  1,  4,  4,  1, 12, 12,  4,  2,  4,  0, 12,
          3,  0]])

In [37]:
torch.tensor([input])

tensor([[ 2, 19, 24, 21,  1,  0,  3, 19, 24, 22,  1,  2, 18,  9, 23,  1,  0,  2,
         20, 24, 12,  5,  1,  3, 18,  9, 23,  1,  0,  2,  4, 22, 22,  1,  0,  3,
         20, 23, 12,  5,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0]])

In [48]:
model(x)[0, 41]

tensor([10.1703,  3.2736, -1.0813, -4.1630, -3.6133, -0.9662, -0.9855,  0.1448,
        -0.9064, -0.7270, -4.0681, -1.7807, -1.5822,  0.4457, -0.5275, -2.3099,
        -0.7672, -0.7972, -2.7789, -2.3718, -0.9146, -3.1871, -0.4148, -1.4765,
        -2.1907], grad_fn=<SelectBackward0>)

In [49]:
model(torch.tensor([input]))[0, 41]

tensor([10.1703,  3.2736, -1.0813, -4.1630, -3.6133, -0.9662, -0.9855,  0.1448,
        -0.9064, -0.7270, -4.0681, -1.7807, -1.5822,  0.4457, -0.5275, -2.3099,
        -0.7672, -0.7972, -2.7789, -2.3718, -0.9146, -3.1871, -0.4148, -1.4765,
        -2.1907], grad_fn=<SelectBackward0>)